set(_CATKIN_CURRENT_PACKAGE "exca200_simulink")
set(exca200_simulink_VERSION "0.0.0")
set(exca200_simulink_MAINTAINER "zhuay <zhuay@todo.todo>")
set(exca200_simulink_PACKAGE_FORMAT "2")
set(exca200_simulink_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "urdf" "xacro")
set(exca200_simulink_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "urdf" "xacro")
set(exca200_simulink_BUILDTOOL_DEPENDS "catkin")
set(exca200_simulink_BUILDTOOL_EXPORT_DEPENDS )
set(exca200_simulink_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "urdf" "xacro")
set(exca200_simulink_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "urdf" "xacro")
set(exca200_simulink_TEST_DEPENDS )
set(exca200_simulink_DOC_DEPENDS )
set(exca200_simulink_URL_WEBSITE "")
set(exca200_simulink_URL_BUGTRACKER "")
set(exca200_simulink_URL_REPOSITORY "")
set(exca200_simulink_DEPRECATED "")